-- 1. Table des CATÉGORIES
create table public.categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  slug text not null unique
);

-- 2. Table des PRODUITS
create table public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  price numeric not null,
  stock integer default 0,
  category_id bigint references public.categories(id) on delete set null,
  images text[] default array[]::text[],
  sold integer default 0,
  is_featured boolean default false
);

-- 3. Table des COMMANDES
create table public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_email text not null,
  total numeric not null,
  status text default 'En cours',
  items jsonb default '[]'::jsonb
);

-- 4. Initialisation des données (Optionnel - Pour ne pas partir de zéro)
insert into public.categories (name, slug) values
('Électronique', 'electronique'),
('Vêtements', 'vetements'),
('Accessoires', 'accessoires'),
('Maison', 'maison');

-- 5. Activer le stockage pour les images (Storage Bucket)
insert into storage.buckets (id, name, public) values ('images', 'images', true);

-- POLICIES (Sécurité simple pour commencer)
-- Lecture publique pour tout le monde
alter table public.categories enable row level security;
create policy "Lecture publique categories" on public.categories for select using (true);

alter table public.products enable row level security;
create policy "Lecture publique products" on public.products for select using (true);

-- Écriture (Insert/Update/Delete) pour tout le monde (pour tester facilement l'admin)
-- ⚠️ En production, il faudra restreindre ça aux admins uniquement
create policy "Ecriture publique categories" on public.categories for all using (true);
create policy "Ecriture publique products" on public.products for all using (true);
create policy "Ecriture publique orders" on public.orders for all using (true);
create policy "Upload images" on storage.objects for insert with check (bucket_id = 'images');
create policy "View images" on storage.objects for select using (bucket_id = 'images');
