-- 1. Mise à jour de la table PROFILES
alter table public.profiles 
add column if not exists address text,
add column if not exists phone text,
add column if not exists city text,
add column if not exists zip text,
add column if not exists loyalty_points int default 0,
add column if not exists loyalty_tier text default 'Bronze';

-- 2. Création de la table FAVORITES
create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  product_id bigint references public.products(id) on delete cascade,
  unique(user_id, product_id)
);

-- 3. Création de la table USER_ADDRESSES
create table if not exists public.user_addresses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  title text not null,
  address text not null,
  city text not null,
  phone text not null
);

-- 4. Création de la table COUPONS
create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  code text unique not null,
  description text,
  discount_percent int not null,
  expires_at timestamp with time zone not null
);

-- 5. Création de la table RETURNS
create table if not exists public.returns (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  order_id bigint references public.orders(id) not null,
  reason text not null,
  status text default 'En attente'
);

-- 6. Sécurité (RLS)
alter table public.favorites enable row level security;
alter table public.user_addresses enable row level security;
alter table public.returns enable row level security;
alter table public.coupons enable row level security;

-- Policies for favorites
create policy "Users can view own favorites" on public.favorites for select using (auth.uid() = user_id);
create policy "Users can add own favorites" on public.favorites for insert with check (auth.uid() = user_id);
create policy "Users can delete own favorites" on public.favorites for delete using (auth.uid() = user_id);

-- Policies for user_addresses
create policy "Users can view own addresses" on public.user_addresses for select using (auth.uid() = user_id);
create policy "Users can add own addresses" on public.user_addresses for insert with check (auth.uid() = user_id);
create policy "Users can delete own addresses" on public.user_addresses for delete using (auth.uid() = user_id);

-- Policies for returns
create policy "Users can view own returns" on public.returns for select using (auth.uid() = user_id);
create policy "Users can add own returns" on public.returns for insert with check (auth.uid() = user_id);

-- Policies for coupons (Viewable by everyone authenticated)
create policy "Authenticated users can view coupons" on public.coupons for select using (auth.role() = 'authenticated');

-- 7. Mise à jour de la table ORDERS
alter table public.orders 
add column if not exists status text default 'En cours',
add column if not exists tracking_number text,
add column if not exists tracking_url text;

-- 8. Note: On garde la table orders telle quelle pour l'instant (user_email).
-- Idéalement on ajoutera user_id plus tard mais cela demande de migrer le code de création de commande.


