-- 1. Create banners table
CREATE TABLE IF NOT EXISTS public.banners (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    category_key text NOT NULL, -- 'Téléphones', 'Vêtements', etc.
    slot text NOT NULL, -- 'main', 'rightTop', 'rightBottom'
    title text,
    description text,
    badge text,
    image_url text,
    bg_color text,
    product_id bigint,
    link text,
    is_active boolean DEFAULT true
);

-- 2. Enable RLS
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;

-- 3. Policies
DROP POLICY IF EXISTS "Public banners are viewable by everyone" ON public.banners;
CREATE POLICY "Public banners are viewable by everyone" ON public.banners
    FOR SELECT USING (is_active = true);

DROP POLICY IF EXISTS "Authenticated can manage banners" ON public.banners;
CREATE POLICY "Authenticated can manage banners" ON public.banners
    FOR ALL USING (auth.role() = 'authenticated');

-- 4. Seed Data (from heroSlots.js)
INSERT INTO public.banners (category_key, slot, title, description, badge, image_url, bg_color, product_id) VALUES
-- Téléphones
('Téléphones', 'main', 'iPhone 17 Pro Max', 'Puissance extrême. Design premium.', 'Nouveau', 'https://images.unsplash.com/photo-1695048133142-1a2043614d8c', 'bg-yellow-400', 1),
('Téléphones', 'main', 'Galaxy S25 Ultra', 'Photo et performance ultime.', 'Best Seller', 'https://images.unsplash.com/photo-1606813902914-3c5c4e9c0d92', 'bg-purple-500', 2),
('Téléphones', 'rightTop', 'MacBook Pro M4', NULL, 'Nouveau', 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8', 'bg-black', 3),
('Téléphones', 'rightTop', 'iPad Pro 2025', NULL, 'Hot', 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04', 'bg-gray-900', 4),
('Téléphones', 'rightBottom', 'Galaxy Buds Pro', NULL, 'Deal', 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df', 'bg-red-600', 5),
('Téléphones', 'rightBottom', 'Apple Watch Ultra', NULL, 'Promo', 'https://images.unsplash.com/photo-1603791440384-56cd371ee9a7', 'bg-green-600', 6),

-- Vêtements
('Vêtements', 'main', 'Nike Air Max 270', 'Confort et style ultime.', 'Nouveau', 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519', 'bg-blue-500', 7),
('Vêtements', 'main', 'Adidas Ultraboost', 'Performance et élégance.', 'Best Seller', 'https://images.unsplash.com/photo-1549298916-b41d501d3772', 'bg-green-500', 8),
('Vêtements', 'rightTop', 'Levi''s Jeans', NULL, 'Nouveau', 'https://images.unsplash.com/photo-1542272604-787c3835535d', 'bg-indigo-600', 9),
('Vêtements', 'rightTop', 'H&M T-Shirt', NULL, 'Hot', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab', 'bg-pink-500', 11),
('Vêtements', 'rightBottom', 'Zara Jacket', NULL, 'Deal', 'https://images.unsplash.com/photo-1551028719-00167b16eac5', 'bg-orange-500', 12),
('Vêtements', 'rightBottom', 'Puma Sneakers', NULL, 'Promo', 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa', 'bg-teal-500', 13),

-- Ordinateurs
('Ordinateurs', 'main', 'MacBook Pro M4', 'Puissance et portabilité.', 'Nouveau', 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8', 'bg-gray-800', 14),
('Ordinateurs', 'main', 'Dell XPS 13', 'Ultrabook premium.', 'Best Seller', 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed', 'bg-blue-600', 15),
('Ordinateurs', 'rightTop', 'iPad Pro 2025', NULL, 'Nouveau', 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04', 'bg-black', 16),
('Ordinateurs', 'rightTop', 'Surface Pro 9', NULL, 'Hot', 'https://images.unsplash.com/photo-1587614295999-6c1a3c6e3e2a', 'bg-gray-700', 17),
('Ordinateurs', 'rightBottom', 'HP Pavilion', NULL, 'Deal', 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853', 'bg-red-500', 18),
('Ordinateurs', 'rightBottom', 'Lenovo ThinkPad', NULL, 'Promo', 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed', 'bg-green-600', 19),

-- Montres
('Montres', 'main', 'Apple Watch Ultra', 'Aventure et fitness.', 'Nouveau', 'https://images.unsplash.com/photo-1603791440384-56cd371ee9a7', 'bg-orange-500', 20),
('Montres', 'main', 'Samsung Galaxy Watch', 'Connectivité ultime.', 'Best Seller', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30', 'bg-purple-600', 21),
('Montres', 'rightTop', 'Garmin Fenix', NULL, 'Nouveau', 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1', 'bg-green-700', 22),
('Montres', 'rightTop', 'Fitbit Versa', NULL, 'Hot', 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6', 'bg-blue-500', 23),
('Montres', 'rightBottom', 'Rolex Submariner', NULL, 'Deal', 'https://images.unsplash.com/photo-1547996160-81dfa63595aa', 'bg-yellow-600', 24),
('Montres', 'rightBottom', 'Casio G-Shock', NULL, 'Promo', 'https://images.unsplash.com/photo-1524592094714-0f0654e20314', 'bg-red-600', 25),

-- Audio
('Audio', 'main', 'Sony WH-1000XM6', 'Audio immersif sans fil.', 'Nouveau', 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad', 'bg-black', 26),
('Audio', 'main', 'Bose QuietComfort', 'Confort et qualité sonore.', 'Best Seller', 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df', 'bg-gray-800', 27),
('Audio', 'rightTop', 'AirPods Pro', NULL, 'Nouveau', 'https://images.unsplash.com/photo-1606220945770-b5b6c2c9b5f1', 'bg-white', 28),
('Audio', 'rightTop', 'JBL Go 3', NULL, 'Hot', 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1', 'bg-blue-600', 29),
('Audio', 'rightBottom', 'Marshall Major III', NULL, 'Deal', 'https://images.unsplash.com/photo-1484704849700-f032a568e944', 'bg-brown-600', 30),
('Audio', 'rightBottom', 'Sennheiser HD 250BT', NULL, 'Promo', 'https://images.unsplash.com/photo-1583394838336-acd977736f90', 'bg-green-600', 31),

-- Gaming
('Gaming', 'main', 'PlayStation 5', 'Jeu next-gen ultime.', 'Nouveau', 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db', 'bg-blue-700', 32),
('Gaming', 'main', 'Xbox Series X', 'Performance et exclusivités.', 'Best Seller', 'https://images.unsplash.com/photo-1621259182978-fbf93132d53d', 'bg-green-600', 33),
('Gaming', 'rightTop', 'Nintendo Switch OLED', NULL, 'Nouveau', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96', 'bg-red-500', 34),
('Gaming', 'rightTop', 'Razer Keyboard', NULL, 'Hot', 'https://images.unsplash.com/photo-1587829741301-dc798b83add3', 'bg-black', 35),
('Gaming', 'rightBottom', 'Logitech Mouse', NULL, 'Deal', 'https://images.unsplash.com/photo-1527814050087-3793815479db', 'bg-gray-600', 36),
('Gaming', 'rightBottom', 'Corsair Headset', NULL, 'Promo', 'https://images.unsplash.com/photo-1599669454699-248893623440', 'bg-purple-600', 37),

-- Electronique
('Electronique', 'main', 'iPad Pro 2025', 'Créativité et productivité.', 'Nouveau', 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04', 'bg-gray-900', 38),
('Electronique', 'main', 'Kindle Paperwhite', 'Lecture immersive.', 'Best Seller', 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570', 'bg-white', 39),
('Electronique', 'rightTop', 'Echo Dot', NULL, 'Nouveau', 'https://images.unsplash.com/photo-1543512214-318c7553f230', 'bg-black', 40),
('Electronique', 'rightTop', 'Ring Doorbell', NULL, 'Hot', 'https://images.unsplash.com/photo-1557804506-669a67965ba0', 'bg-blue-500', 41),
('Electronique', 'rightBottom', 'GoPro Hero 10', NULL, 'Deal', 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0', 'bg-red-600', 42),
('Electronique', 'rightBottom', 'DJI Drone', NULL, 'Promo', 'https://images.unsplash.com/photo-1473968512647-3e447244af8f', 'bg-green-600', 43);
