-- 1. Ensure 'brand' column exists in products
ALTER TABLE public.products 
ADD COLUMN IF NOT EXISTS brand text DEFAULT 'Generic';

-- 2. Create brands table if not exists
CREATE TABLE IF NOT EXISTS public.brands (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    name text NOT NULL,
    slug text NOT NULL UNIQUE,
    logo text,
    is_featured boolean DEFAULT true
);

-- 3. Enable RLS on brands
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;

-- 4. Policies (Drop first to avoid errors if they exist)
DROP POLICY IF EXISTS "Public brands are viewable by everyone" ON public.brands;
CREATE POLICY "Public brands are viewable by everyone" ON public.brands
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated can manage brands" ON public.brands;
CREATE POLICY "Authenticated can manage brands" ON public.brands
    FOR ALL USING (auth.role() = 'authenticated');

-- 5. Insert Seed Data
INSERT INTO public.brands (name, slug, logo) VALUES
('Apple', 'apple', 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg'),
('Samsung', 'samsung', 'https://upload.wikimedia.org/wikipedia/commons/2/24/Samsung_Logo.svg'),
('Sony', 'sony', 'https://upload.wikimedia.org/wikipedia/commons/c/ca/Sony_logo.svg'),
('Nike', 'nike', 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Logo_NIKE.svg'),
('Adidas', 'adidas', 'https://upload.wikimedia.org/wikipedia/commons/2/20/Adidas_Logo.svg'),
('Zara', 'zara', 'https://upload.wikimedia.org/wikipedia/commons/f/fd/Zara_Logo.svg'),
('Dell', 'dell', 'https://upload.wikimedia.org/wikipedia/commons/4/48/Dell_Logo.svg'),
('HP', 'hp', 'https://upload.wikimedia.org/wikipedia/commons/a/ad/HP_logo_2012.svg'),
('Microsoft', 'microsoft', 'https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg'),
('Lenovo', 'lenovo', 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Lenovo_logo_2015.svg'),
('Intel', 'intel', 'https://upload.wikimedia.org/wikipedia/commons/e/e8/Intel_logo.svg'),
('Xiaomi', 'xiaomi', 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Xiaomi_logo_%282021-%29.svg'),
('LG', 'lg', 'https://upload.wikimedia.org/wikipedia/commons/b/bf/LG_logo_%282015%29.svg'),
('Puma', 'puma', 'https://upload.wikimedia.org/wikipedia/commons/a/a5/Puma_Logo.svg')
ON CONFLICT (slug) DO UPDATE 
SET logo = EXCLUDED.logo, name = EXCLUDED.name;
