import {
  Smartphone,
  Tablet,
  Laptop,
  Camera,
  Headphones,
  Speaker,
  Tv,
  Printer,
  Watch,
  Shirt,
  Footprints,
  Gem,
  Glasses,
  Briefcase,
  Umbrella,
  Baby,
  Home,
  Armchair,
  Bed,
  Lamp,
  Flower2,
  Hammer,
  Wrench,
  Utensils,
  ChefHat,
  Sparkles,
  SprayCan,
  Heart,
  Pill,
  Palette,
  Gamepad2,
  Book,
  Music,
  Clapperboard,
  Bike,
  Dumbbell,
  Tent,
  Trophy,
  Gift,
  Car,
  PawPrint,
  Apple,
  Coffee,
  ShoppingBag,
  Monitor,
} from "lucide-react";

export const categoryUI = {
  // Electronics
  telephones: { icon: Smartphone },
  phones: { icon: Smartphone },
  smartphones: { icon: Smartphone },
  tablettes: { icon: Tablet },
  tablets: { icon: Tablet },
  informatique: { icon: Laptop },
  computers: { icon: Laptop },
  laptops: { icon: Laptop },
  pc: { icon: Monitor },
  photo: { icon: Camera },
  cameras: { icon: Camera },
  audio: { icon: Headphones },
  casques: { icon: Headphones },
  headphones: { icon: Headphones },
  enceintes: { icon: Speaker },
  speakers: { icon: Speaker },
  tv: { icon: Tv },
  television: { icon: Tv },
  imprimantes: { icon: Printer },
  printers: { icon: Printer },

  // Fashion
  vetements: { icon: Shirt },
  clothing: { icon: Shirt },
  mode: { icon: Shirt },
  chaussures: { icon: Footprints },
  shoes: { icon: Footprints },
  sneakers: { icon: Footprints },
  accessoires: { icon: Gem },
  accessories: { icon: Gem },
  bijoux: { icon: Gem },
  jewelry: { icon: Gem },
  montres: { icon: Watch },
  montre: { icon: Watch },
  watches: { icon: Watch },
  lunettes: { icon: Glasses },
  glasses: { icon: Glasses },
  sacs: { icon: Briefcase },
  bags: { icon: ShoppingBag },
  bebe: { icon: Baby },
  baby: { icon: Baby },

  // Home & Garden
  maison: { icon: Home },
  home: { icon: Home },
  meubles: { icon: Armchair },
  furniture: { icon: Armchair },
  canape: { icon: Armchair },
  lit: { icon: Bed },
  bedding: { icon: Bed },
  decoration: { icon: Lamp },
  deco: { icon: Lamp },
  jardin: { icon: Flower2 },
  garden: { icon: Flower2 },
  bricolage: { icon: Hammer },
  diy: { icon: Hammer },
  outils: { icon: Wrench },
  tools: { icon: Wrench },
  cuisine: { icon: Utensils },
  kitchen: { icon: ChefHat },

  // Beauty & Health
  beaute: { icon: Sparkles },
  beauty: { icon: Sparkles },
  maquillage: { icon: Palette },
  makeup: { icon: Palette },
  parfum: { icon: SprayCan },
  perfume: { icon: SprayCan },
  sante: { icon: Heart },
  health: { icon: Heart },
  pharmacie: { icon: Pill },

  // Hobbies & Entertainment
  jeux: { icon: Gamepad2 },
  gaming: { icon: Gamepad2 },
  consoles: { icon: Gamepad2 },
  livres: { icon: Book },
  books: { icon: Book },
  musique: { icon: Music },
  music: { icon: Music },
  films: { icon: Clapperboard },
  movies: { icon: Clapperboard },
  sport: { icon: Dumbbell },
  fitness: { icon: Dumbbell },
  velo: { icon: Bike },
  cycling: { icon: Bike },
  camping: { icon: Tent },
  outdoor: { icon: Tent },
  trophees: { icon: Trophy },

  // Other
  auto: { icon: Car },
  moto: { icon: Car },
  animaux: { icon: PawPrint },
  pets: { icon: PawPrint },
  alimentation: { icon: Apple },
  food: { icon: Apple },
  boissons: { icon: Coffee },
  drinks: { icon: Coffee },
  cadeaux: { icon: Gift },
  gifts: { icon: Gift },
  soldes: { icon: Gift },
};
