export const EXCHANGE_RATES = {
  FCFA: 1,
  EUR: 0.001524, // Officiel (1/655.957)
  USD: 0.0016,   // Marché (1/625)
  USDT: 0.0015,  // P2P/Crypto avec frais (1/666)
};

export const translations = {
  fr: {
    welcome: "Bienvenue",
    home: "Accueil",
    shop: "Boutique",
    cart: "Panier",
    favorites: "Favoris",
    search: "Rechercher...",
    add_to_cart: "Ajouter au panier",
    remove_from_cart: "Retirer du panier",
    quantity: "Quantité",
    product: "Produit",
    categories: "Catégories",
    featured_products: "Produits en vedette",
    popular_brands: "Marques populaires",
    help: "Aide",
    profile: "Profil",
    logout: "Déconnexion",
    login: "Connexion",
    register: "S'inscrire",
    no_products: "Aucun produit trouvé",
    price: "Prix",
    total: "Total",
    checkout: "Commander",
    subtotal: "Sous-total",
    shipping: "Frais de livraison",
    order_summary: "Résumé de la commande",
    dashboard: "Tableau de bord",
    admin: "Admin",
    buy_now: "Acheter maintenant",
    stock_out: "Rupture de stock",
    in_favorites: "Dans vos favoris",
    add_favorites: "Ajouter aux favoris",
    share: "Partager",
    description: "Description",
    delivery_returns: "Livraison & Retours",
    reviews: "Avis",
    similar_products: "Vous aimerez aussi",
    promo: "Promo",
    size: "Taille",
    write_review: "Écrire un avis",
    select_size: "Veuillez sélectionner une taille",
    all_products: "Tous les produits",
    budget: "Budget",
    reset: "Réinitialiser",
    sort_by: "Trier par",
    new_arrivals: "Nouveautés",
    price_asc: "Prix croissant",
    price_desc: "Prix décroissant",
    popularity: "Popularité",
    see_all: "Tout voir",
    items: "article",
    clear_all: "Tout effacer",
    filters: "Filtres",
    search_placeholder: "Rechercher un produit...",
    delivery_info: "Informations de livraison",
    contact_info: "Coordonnées",
    shipping_address: "Adresse de livraison",
    shipping_method: "Mode de livraison",
    payment: "Paiement",
    place_order: "Passer la commande",
    order_confirmed: "Commande confirmée",
    first_name: "Prénom",
    last_name: "Nom",
    email_address: "Adresse e-mail",
    address_placeholder: "Adresse (Numéro, Rue)",
    city: "Ville",
    phone: "Téléphone",
    save_info: "Sauvegarder mes informations",
    already_have_account: "Déjà un compte ?",
    standard_shipping: "Standard",
    express_shipping: "Express",
    pay_now: "Payer maintenant",
    continue: "Continuer",
    back_to_cart: "Retour au panier",
    order_summary_show: "Afficher le sommaire",
    order_summary_hide: "Masquer le sommaire",
    login_title: "Bon retour 👋",
    login_subtitle: "Connectez-vous à votre compte",
    email_label: "Adresse email",
    password_label: "Mot de passe",
    login_button: "Se connecter",
    no_account: "Pas encore de compte ?",
    create_account: "Créer un compte",
    register_title: "Créer un compte ✨",
    register_subtitle: "Rejoignez-nous aujourd'hui",
    full_name: "Nom complet",
    register_button: "S'inscrire",
    already_account: "Déjà un compte ?",
    log_in: "Se connecter",
    confirm_password: "Confirmer le mot de passe",
    create_account_button: "Créer mon compte",
    passwords_dont_match: "Les mots de passe ne correspondent pas",
    account_created_check_email: "Compte créé ! Veuillez vérifier votre email pour confirmer.",
    language_label: "Langue",
    currency_label: "Devise",
    menu: "Menu",
    fast_delivery: "Livraison rapide partout",
    secure_payment: "Paiement 100% sécurisé",
    payment_methods_mobile: "Mobile Money & Cartes",
    customer_support: "Support client 7j/7",
    footer_mission: "est une marketplace en ligne qui vous permet d’acheter facilement des produits authentiques : électronique, mode, sport, beauté, maison et bien plus encore.",
    buy_on: "Acheter sur",
    services_help: "Services & Aide",
    popular_categories: "Catégories populaires",
    how_to_order: "Comment commander",
    payment_methods: "Modes de paiement",
    order_tracking: "Suivi de commande",
    help_center: "Centre d’aide",
    returns_refunds: "Retours & remboursements",
    terms_of_use: "Conditions d’utilisation",
    privacy_policy: "Politique de confidentialité",
    all_rights_reserved: "Tous droits réservés.",
    order_now: "Commander",
    analyzing: "Analyse...",
    shoes_label: "Chaussures",
    dresses_label: "Robes",
    no_results_for: "Aucun résultat pour",
    see_all_results: "Voir tous les résultats",
  },
  en: {
    welcome: "Welcome",
    home: "Home",
    shop: "Shop",
    cart: "Cart",
    favorites: "Favorites",
    search: "Search...",
    add_to_cart: "Add to cart",
    remove_from_cart: "Remove from cart",
    quantity: "Quantity",
    product: "Product",
    categories: "Categories",
    featured_products: "Featured Products",
    popular_brands: "Popular Brands",
    help: "Help",
    profile: "Profile",
    logout: "Logout",
    login: "Login",
    register: "Register",
    no_products: "No products found",
    price: "Price",
    total: "Total",
    checkout: "Checkout",
    subtotal: "Subtotal",
    shipping: "Shipping",
    order_summary: "Order Summary",
    dashboard: "Dashboard",
    admin: "Admin",
    buy_now: "Buy now",
    stock_out: "Out of stock",
    in_favorites: "In favorites",
    add_favorites: "Add to favorites",
    share: "Share",
    description: "Description",
    delivery_returns: "Delivery & Returns",
    reviews: "Reviews",
    similar_products: "You may also like",
    promo: "Promo",
    size: "Size",
    write_review: "Write a review",
    select_size: "Please select a size",
    all_products: "All products",
    budget: "Budget",
    reset: "Reset",
    sort_by: "Sort by",
    new_arrivals: "New arrivals",
    price_asc: "Price: Low to High",
    price_desc: "Price: High to Low",
    popularity: "Popularity",
    see_all: "See all",
    items: "item",
    clear_all: "Clear all",
    filters: "Filters",
    search_placeholder: "Search for a product...",
    delivery_info: "Delivery Information",
    contact_info: "Contact Information",
    shipping_address: "Shipping Address",
    shipping_method: "Shipping Method",
    payment: "Payment",
    place_order: "Place Order",
    order_confirmed: "Order Confirmed",
    first_name: "First Name",
    last_name: "Last Name",
    email_address: "Email Address",
    address_placeholder: "Address (Number, Street)",
    city: "City",
    phone: "Phone",
    save_info: "Save my information",
    already_have_account: "Already have an account?",
    standard_shipping: "Standard",
    express_shipping: "Express",
    pay_now: "Pay now",
    continue: "Continue",
    back_to_cart: "Back to cart",
    order_summary_show: "Show order summary",
    order_summary_hide: "Hide order summary",
    login_title: "Welcome back 👋",
    login_subtitle: "Log in to your account",
    email_label: "Email address",
    password_label: "Password",
    login_button: "Log in",
    no_account: "Don't have an account?",
    create_account: "Create an account",
    register_title: "Create an account ✨",
    register_subtitle: "Join us today",
    full_name: "Full name",
    register_button: "Register",
    already_account: "Already have an account?",
    log_in: "Log in",
    confirm_password: "Confirm password",
    create_account_button: "Create my account",
    passwords_dont_match: "Passwords don't match",
    account_created_check_email: "Account created! Please check your email to confirm.",
    language_label: "Language",
    currency_label: "Currency",
    menu: "Menu",
    fast_delivery: "Fast delivery everywhere",
    secure_payment: "100% Secure payment",
    payment_methods_mobile: "Mobile Money & Cards",
    customer_support: "7/7 Customer support",
    footer_mission: "is an online marketplace that allows you to easily buy authentic products: electronics, fashion, sports, beauty, home and much more.",
    buy_on: "Buy on",
    services_help: "Services & Help",
    popular_categories: "Popular categories",
    how_to_order: "How to order",
    payment_methods: "Payment methods",
    order_tracking: "Order tracking",
    help_center: "Help center",
    returns_refunds: "Returns & refunds",
    terms_of_use: "Terms of use",
    privacy_policy: "Privacy policy",
    all_rights_reserved: "All rights reserved.",
    order_now: "Order Now",
    analyzing: "Analyzing...",
    shoes_label: "Shoes",
    dresses_label: "Dresses",
    no_results_for: "No results for",
    see_all_results: "See all results",
  }
};
