export const EXCHANGE_RATES = {
  FCFA: 1,
  EUR: 0.001524, // Officiel (1/655.957)
  USD: 0.0016,   // Marché (1/625)
  USDT: 0.0015,  // P2P/Crypto avec frais (1/666)
};

export const translations = {
  fr: {
    best_selling_products: "Produits les plus vendus",
    // Dynamic Categories
    "Telephones": "Téléphones",
    "Téléphones": "Téléphones",
    "Chaussures": "Chaussures",
    "Jeux": "Jeux",
    "Maison": "Maison",
    "Parfum": "Parfum",
    "Sport": "Sport",
    "Vêtements": "Vêtements",
    "Vetements": "Vêtements",
    "VETEMENTS": "Vêtements",
    "Ordinateurs": "Ordinateurs",
    "Mode": "Mode",
    "Beauté": "Beauté",
    "Santé": "Santé",
    "Autres": "Autres",
    welcome: "Bienvenue",
    home: "Accueil",
    shop: "Boutique",
    cart: "Panier",

    favorites: "Favoris",
    search: "Rechercher...",
    add_to_cart: "Ajouter au panier",
    added_to_cart: "Ajouté au panier",
    remove_from_cart: "Retirer du panier",
    quantity: "Quantité",
    product: "Produit",
    categories: "Catégories",
    featured_products: "Produits en vedette",
    popular_brands: "Marques populaires",
    help: "Aide",
    profile: "Profil",
    logout: "Déconnexion",
    login: "Connexion",
    register: "S'inscrire",
    no_products: "Aucun produit trouvé",
    price: "Prix",
    total: "Total",
    checkout: "Commander",
    subtotal: "Sous-total",
    shipping: "Frais de livraison",
    order_summary: "Résumé de la commande",
    dashboard: "Tableau de bord",
    admin: "Admin",
    buy_now: "Acheter maintenant",
    stock_out: "Rupture de stock",
    in_favorites: "Dans vos favoris",
    add_favorites: "Ajouter aux favoris",
    share: "Partager",
    description: "Description",
    delivery_returns: "Livraison & Retours",
    reviews: "Avis",
    similar_products: "Vous aimerez aussi",
    promo: "Promo",
    size: "Taille",
    write_review: "Écrire un avis",
    select_size: "Veuillez sélectionner une taille",
    all_products: "Tous les produits",
    budget: "Budget",
    reset: "Réinitialiser",
    sort_by: "Trier par",
    new_arrivals: "Nouveautés",
    price_asc: "Prix croissant",
    price_desc: "Prix décroissant",
    popularity: "Popularité",
    see_all: "Tout voir",
    items: "article",
    clear_all: "Tout effacer",
    filters: "Filtres",
    search_placeholder: "Rechercher un produit...",
    delivery_info: "Informations de livraison",
    contact_info: "Coordonnées",
    shipping_address: "Adresse de livraison",
    shipping_method: "Mode de livraison",
    payment: "Paiement",
    place_order: "Passer la commande",
    order_confirmed: "Commande confirmée",
    first_name: "Prénom",
    last_name: "Nom",
    email_address: "Adresse e-mail",
    address_placeholder: "Adresse (Numéro, Rue)",
    city: "Ville",
    phone: "Téléphone",
    save_info: "Sauvegarder mes informations",
    already_have_account: "Déjà un compte ?",
    standard_shipping: "Standard",
    express_shipping: "Express",
    pay_now: "Payer maintenant",
    continue: "Continuer",
    back_to_cart: "Retour au panier",
    order_summary_show: "Afficher le sommaire",
    order_summary_hide: "Masquer le sommaire",
    login_title: "Bon retour 👋",
    login_subtitle: "Connectez-vous à votre compte",
    email_label: "Adresse email",
    password_label: "Mot de passe",
    login_button: "Se connecter",
    no_account: "Pas encore de compte ?",
    create_account: "Créer un compte",
    register_title: "Créer un compte ✨",
    register_subtitle: "Rejoignez-nous aujourd'hui",
    full_name: "Nom complet",
    register_button: "S'inscrire",
    already_account: "Déjà un compte ?",
    log_in: "Se connecter",
    confirm_password: "Confirmer le mot de passe",
    create_account_button: "Créer mon compte",
    passwords_dont_match: "Les mots de passe ne correspondent pas",
    account_created_check_email: "Compte créé ! Veuillez vérifier votre email pour confirmer.",
    language_label: "Langue",
    currency_label: "Devise",
    menu: "Menu",
    fast_delivery: "Livraison rapide partout",
    secure_payment: "Paiement 100% sécurisé",
    payment_methods_mobile: "Mobile Money & Cartes",
    customer_support: "Support client 7j/7",
    footer_mission: "est une marketplace en ligne qui vous permet d’acheter facilement des produits authentiques : électronique, mode, sport, beauté, maison et bien plus encore.",
    buy_on: "Acheter sur",
    services_help: "Services & Aide",
    popular_categories: "Catégories populaires",
    how_to_order: "Comment commander",
    payment_methods: "Modes de paiement",
    order_tracking: "Suivi de commande",
    help_center: "Centre d’aide",
    returns_refunds: "Retours & remboursements",
    terms_of_use: "Conditions d’utilisation",
    privacy_policy: "Politique de confidentialité",
    all_rights_reserved: "Tous droits réservés.",
    order_now: "Commander",
    analyzing: "Analyse...",
    shoes_label: "Chaussures",
    dresses_label: "Robes",
    no_results_for: "Aucun résultat pour",
    see_all_results: "Voir tous les résultats",
    // Help Page
    delivery: "Livraison",
    tracking_and_delays: "Suivi & Délais",
    returns: "Retours",
    refunds: "Remboursements",
    payment_help: "Paiement",
    secure_and_mobile: "Sécurisé & Mobile",
    my_account: "Mon Compte",
    orders_and_info: "Commandes & Infos",
    faq_title: "Questions Fréquentes",
    faq_subtitle: "Les réponses aux questions les plus posées par nos clients.",
    cant_find_answer: "Vous ne trouvez pas votre réponse ?",
    need_more_help: "Besoin d'aide supplémentaire ?",
    contact_us: "Contactez-nous",
    // General
    loading: "Chargement...",
    error_occurred: "Une erreur est survenue",
    success: "Succès",
    save: "Sauvegarder",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    view_details: "Voir détails",
    status: "Statut",
    date: "Date",
    actions: "Actions",
    no_orders: "Aucune commande trouvée",
    pending: "En attente",
    processing: "En cours de traitement",
    shipped: "Expédié",
    delivered: "Livré",
    cancelled: "Annulé",
    refunded: "Remboursé",
    returned: "Retourné",
    view_order: "Voir commande",
    track_order: "Suivre commande",
    download_invoice: "Télécharger facture",
    address_book: "Carnet d'adresses",
    add_new_address: "Ajouter une nouvelle adresse",
    default_address: "Adresse par défaut",
    set_as_default: "Définir comme par défaut",
    confirm_delete: "Êtes-vous sûr de vouloir supprimer ?",
    yes_delete: "Oui, supprimer",
    no_cancel: "Non, annuler",
    personal_info: "Informations personnelles",
    change_password: "Changer mot de passe",
    current_password: "Mot de passe actuel",
    new_password: "Nouveau mot de passe",
    update_profile: "Mettre à jour le profil",
    profile_updated: "Profil mis à jour avec succès",
    password_updated: "Mot de passe mis à jour avec succès",
    reviews_title: "Avis Clients",
    no_reviews_yet: "Pas encore d'avis",
    be_first_review: "Soyez le premier à donner votre avis !",
    rating: "Note",
    comment: "Commentaire",
    submit_review: "Soumettre l'avis",
    review_submitted: "Avis soumis avec succès",
    thank_you_review: "Merci pour votre avis !",
    verified_purchase: "Achat vérifié",
    related_products: "Produits similaires",
    view_cart: "Voir le panier",
    empty_cart: "Votre panier est vide",
    start_shopping: "Commencer vos achats",
    apply_coupon: "Appliquer un code promo",
    coupon_code: "Code promo",
    discount: "Réduction",
    invalid_coupon: "Code promo invalide",
    coupon_applied: "Code promo appliqué !",
    remove_coupon: "Retirer",
    guest_checkout: "Commande invité",
    login_checkout: "Connexion pour commander",
    or: "Ou",
    secure_transaction: "Transaction sécurisée",
    privacy_notice: "Vos données sont protégées.",
    terms_conditions: "Conditions générales",
    subscribe_newsletter: "S'inscrire à la newsletter",
    newsletter_placeholder: "Votre adresse email",
    subscribe: "S'inscrire",
    subscribed_success: "Inscription réussie !",
    about_us: "À propos de nous",
    careers: "Carrières",
    blog: "Blog",
    partners: "Partenaires",
    sitemap: "Plan du site",
    cookie_policy: "Politique de cookies",
    settings: "Paramètres",
    notifications: "Notifications",
    mark_all_read: "Tout marquer comme lu",
    no_notifications: "Pas de nouvelles notifications",
    back_to_home: "Retour à l'accueil",
    page_not_found: "Page introuvable",
    error_404_msg: "Désolé, la page que vous recherchez n'existe pas.",
    go_home: "Aller à l'accueil",
    retry: "Réessayer",
    network_error: "Erreur réseau",
    maintenance_mode: "Mode maintenance",
    coming_soon: "Bientôt disponible",
  },
  en: {
    best_selling_products: "Best selling products",
    // Dynamic Categories
    "Telephones": "Phones",
    "Téléphones": "Phones",
    "Chaussures": "Shoes",
    "Jeux": "Games",
    "Maison": "Home",
    "Parfum": "Perfume",
    "Sport": "Sport",
    "Vêtements": "Clothing",
    "Vetements": "Clothing",
    "VETEMENTS": "Clothing",
    "Ordinateurs": "Computers",
    "Mode": "Fashion",
    "Beauté": "Beauty",
    "Santé": "Health",
    "Autres": "Others",
    welcome: "Welcome",
    home: "Home",
    shop: "Shop",
    cart: "Cart",
    favorites: "Favorites",
    search: "Search...",
    add_to_cart: "Add to cart",
    added_to_cart: "Added to cart",
    remove_from_cart: "Remove from cart",
    quantity: "Quantity",
    product: "Product",
    categories: "Categories",
    featured_products: "Featured Products",
    popular_brands: "Popular Brands",
    help: "Help",
    profile: "Profile",
    logout: "Logout",
    login: "Login",
    register: "Register",
    no_products: "No products found",
    price: "Price",
    total: "Total",
    checkout: "Checkout",
    subtotal: "Subtotal",
    shipping: "Shipping",
    order_summary: "Order Summary",
    dashboard: "Dashboard",
    admin: "Admin",
    buy_now: "Buy now",
    stock_out: "Out of stock",
    in_favorites: "In favorites",
    add_favorites: "Add to favorites",
    share: "Share",
    description: "Description",
    delivery_returns: "Delivery & Returns",
    reviews: "Reviews",
    similar_products: "You may also like",
    promo: "Promo",
    size: "Size",
    write_review: "Write a review",
    select_size: "Please select a size",
    all_products: "All products",
    budget: "Budget",
    reset: "Reset",
    sort_by: "Sort by",
    new_arrivals: "New arrivals",
    price_asc: "Price: Low to High",
    price_desc: "Price: High to Low",
    popularity: "Popularity",
    see_all: "See all",
    items: "item",
    clear_all: "Clear all",
    filters: "Filters",
    search_placeholder: "Search for a product...",
    delivery_info: "Delivery Information",
    contact_info: "Contact Information",
    shipping_address: "Shipping Address",
    shipping_method: "Shipping Method",
    payment: "Payment",
    place_order: "Place Order",
    order_confirmed: "Order Confirmed",
    first_name: "First Name",
    last_name: "Last Name",
    email_address: "Email Address",
    address_placeholder: "Address (Number, Street)",
    city: "City",
    phone: "Phone",
    save_info: "Save my information",
    already_have_account: "Already have an account?",
    standard_shipping: "Standard",
    express_shipping: "Express",
    pay_now: "Pay now",
    continue: "Continue",
    back_to_cart: "Back to cart",
    order_summary_show: "Show order summary",
    order_summary_hide: "Hide order summary",
    login_title: "Welcome back 👋",
    login_subtitle: "Log in to your account",
    email_label: "Email address",
    password_label: "Password",
    login_button: "Log in",
    no_account: "Don't have an account?",
    create_account: "Create an account",
    register_title: "Create an account ✨",
    register_subtitle: "Join us today",
    full_name: "Full name",
    register_button: "Register",
    already_account: "Already have an account?",
    log_in: "Log in",
    confirm_password: "Confirm password",
    create_account_button: "Create my account",
    passwords_dont_match: "Passwords don't match",
    account_created_check_email: "Account created! Please check your email to confirm.",
    language_label: "Language",
    currency_label: "Currency",
    menu: "Menu",
    fast_delivery: "Fast delivery everywhere",
    secure_payment: "100% Secure payment",
    payment_methods_mobile: "Mobile Money & Cards",
    customer_support: "7/7 Customer support",
    footer_mission: "is an online marketplace that allows you to easily buy authentic products: electronics, fashion, sports, beauty, home and much more.",
    buy_on: "Buy on",
    services_help: "Services & Help",
    popular_categories: "Popular categories",
    how_to_order: "How to order",
    payment_methods: "Payment methods",
    order_tracking: "Order tracking",
    help_center: "Help center",
    returns_refunds: "Returns & refunds",
    terms_of_use: "Terms of use",
    privacy_policy: "Privacy policy",
    all_rights_reserved: "All rights reserved.",
    order_now: "Order Now",
    analyzing: "Analyzing...",
    shoes_label: "Shoes",
    dresses_label: "Dresses",
    no_results_for: "No results for",
    see_all_results: "See all results",
     // Help Page
    delivery: "Delivery",
    tracking_and_delays: "Tracking & Delays",
    returns: "Returns",
    refunds: "Refunds",
    payment_help: "Payment",
    secure_and_mobile: "Secure & Mobile",
    my_account: "My Account",
    orders_and_info: "Orders & Info",
    faq_title: "Frequently Asked Questions",
    faq_subtitle: "Answers to the most frequently asked questions by our customers.",
    cant_find_answer: "Can't find your answer?",
    need_more_help: "Need more help?",
    contact_us: "Contact us",
    // General
    loading: "Loading...",
    error_occurred: "An error occurred",
    success: "Success",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    view_details: "View details",
    status: "Status",
    date: "Date",
    actions: "Actions",
    no_orders: "No orders found",
    pending: "Pending",
    processing: "Processing",
    shipped: "Shipped",
    delivered: "Delivered",
    cancelled: "Cancelled",
    refunded: "Refunded",
    returned: "Returned",
    view_order: "View order",
    track_order: "Track order",
    download_invoice: "Download invoice",
    address_book: "Address Book",
    add_new_address: "Add new address",
    default_address: "Default address",
    set_as_default: "Set as default",
    confirm_delete: "Are you sure you want to delete?",
    yes_delete: "Yes, delete",
    no_cancel: "No, cancel",
    personal_info: "Personal Information",
    change_password: "Change password",
    current_password: "Current password",
    new_password: "New password",
    update_profile: "Update profile",
    profile_updated: "Profile updated successfully",
    password_updated: "Password updated successfully",
    reviews_title: "Customer Reviews",
    no_reviews_yet: "No reviews yet",
    be_first_review: "Be the first to review!",
    rating: "Rating",
    comment: "Comment",
    submit_review: "Submit review",
    review_submitted: "Review submitted successfully",
    thank_you_review: "Thank you for your review!",
    verified_purchase: "Verified Purchase",
    related_products: "Related Products",
    view_cart: "View cart",
    empty_cart: "Your cart is empty",
    start_shopping: "Start shopping",
    apply_coupon: "Apply coupon code",
    coupon_code: "Coupon code",
    discount: "Discount",
    invalid_coupon: "Invalid coupon code",
    coupon_applied: "Coupon applied!",
    remove_coupon: "Remove",
    guest_checkout: "Guest Checkout",
    login_checkout: "Login to Checkout",
    or: "Or",
    secure_transaction: "Secure transaction",
    privacy_notice: "Your data is protected.",
    terms_conditions: "Terms & Conditions",
    subscribe_newsletter: "Subscribe to newsletter",
    newsletter_placeholder: "Your email address",
    subscribe: "Subscribe",
    subscribed_success: "Subscribed successfully!",
    about_us: "About Us",
    careers: "Careers",
    blog: "Blog",
    partners: "Partners",
    sitemap: "Sitemap",
    cookie_policy: "Cookie Policy",
    settings: "Settings",
    notifications: "Notifications",
    mark_all_read: "Mark all as read",
    no_notifications: "No new notifications",
    back_to_home: "Back to home",
    page_not_found: "Page Not Found",
    error_404_msg: "Sorry, the page you are looking for does not exist.",
    go_home: "Go to Home",
    retry: "Retry",
    network_error: "Network error",
    maintenance_mode: "Maintenance mode",
    coming_soon: "Coming soon",
  }
};
